name: Daily Commit Action

on:
  schedule:
    - cron: '30 4 * * *'  # Runs daily at 04:30 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Append for 23f1000333@ds.study.iitm.ac.in
        run: |
          echo "Workflow ran at $(date -u)" >> commit-log.txt

      - name: Commit step for 23f1000333@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "23f1000333@ds.study.iitm.ac.in"
          git add commit-log.txt
          git commit -m "Auto commit from GitHub Action on $(date -u)" || echo "No changes"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
