name: Daily Commit

on:
  schedule:
    - cron: '17 5 * * *'  # Runs every day at 05:17 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a change - 23f1000333@ds.study.iitm.ac.in
        run: |
          date >> daily-log.txt
          git config --global user.email "23f1000333@ds.study.iitm.ac.in"
          git config --global user.name "DevSync Bot"
          git add daily-log.txt
          git commit -m "Daily update $(date)"
          git push
